export interface CatalogEntry {
  readonly name: string
  readonly description: string
  readonly category: 'alias' | 'completion' | 'utility' | 'hook'
  readonly omzName: string
  readonly platform?: 'macos' | 'linux' | 'all'
  readonly status: 'full' | 'partial' | 'no-equivalent'
}

export const PLUGIN_CATALOG: readonly CatalogEntry[] = [
  // ── Already ported (Phases 8-11) ──────────────────────────────────
  { name: 'git', description: 'Git aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'git', status: 'full' },
  { name: 'git-completions', description: 'Git completions with branch/tag/remote support', category: 'completion', omzName: 'git', status: 'full' },
  { name: 'docker-completions', description: 'Docker CLI completions', category: 'completion', omzName: 'docker', status: 'full' },
  { name: 'npm-completions', description: 'npm CLI completions', category: 'completion', omzName: 'npm', status: 'full' },
  { name: 'kubectl-completions', description: 'kubectl CLI completions', category: 'completion', omzName: 'kubectl', status: 'full' },
  { name: 'cloud-completions', description: 'Cloud CLI completions (aws, gcloud, az)', category: 'completion', omzName: 'aws', status: 'full' },
  { name: 'devtools-completions', description: 'Developer tools completions', category: 'completion', omzName: 'node', status: 'full' },
  { name: 'sysadmin-completions', description: 'System admin completions', category: 'completion', omzName: 'systemd', status: 'full' },
  { name: 'extract', description: 'Extract archives with a single command', category: 'utility', omzName: 'extract', status: 'full' },
  { name: 'sudo', description: 'Press Escape twice to add sudo to current command', category: 'utility', omzName: 'sudo', status: 'full' },
  { name: 'copypath', description: 'Copy current directory path to clipboard', category: 'utility', omzName: 'copypath', status: 'full' },
  { name: 'encode64', description: 'Base64 encode/decode aliases', category: 'utility', omzName: 'encode64', status: 'full' },
  { name: 'urltools', description: 'URL encode/decode utilities', category: 'utility', omzName: 'urltools', status: 'full' },
  { name: 'jsontools', description: 'JSON formatting and manipulation', category: 'utility', omzName: 'jsontools', status: 'full' },
  { name: 'web-search', description: 'Search the web from the terminal', category: 'utility', omzName: 'web-search', status: 'full' },
  { name: 'dirhistory', description: 'Navigate directory history with Alt+arrow keys', category: 'utility', omzName: 'dirhistory', status: 'full' },

  // ── New alias plugins (Phase 12 batch generation) ─────────────────
  { name: 'ansible', description: 'Ansible aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'ansible', status: 'full' },
  { name: 'arcanist', description: 'Arcanist aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'arcanist', status: 'full' },
  { name: 'argocd', description: 'Argo CD aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'argocd', status: 'full' },
  { name: 'aws', description: 'AWS CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'aws', status: 'partial', platform: 'all' },
  { name: 'azure', description: 'Azure CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'azure', status: 'full' },
  { name: 'bazel', description: 'Bazel aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'bazel', status: 'full' },
  { name: 'bun', description: 'Bun runtime aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'bun', status: 'full' },
  { name: 'bundler', description: 'Ruby Bundler aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'bundler', status: 'full' },
  { name: 'capistrano', description: 'Capistrano aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'capistrano', status: 'full' },
  { name: 'chezmoi', description: 'Chezmoi dotfile manager aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'chezmoi', status: 'full' },
  { name: 'cloudfoundry', description: 'Cloud Foundry aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'cloudfoundry', status: 'full' },
  { name: 'common-aliases', description: 'Common shell aliases (portable subset)', category: 'alias', omzName: 'common-aliases', status: 'partial' },
  { name: 'composer', description: 'PHP Composer aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'composer', status: 'full' },
  { name: 'dbt', description: 'dbt aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'dbt', status: 'full' },
  { name: 'debian', description: 'Debian/apt aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'debian', status: 'partial', platform: 'linux' },
  { name: 'deno', description: 'Deno aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'deno', status: 'full' },
  { name: 'docker-compose', description: 'Docker Compose aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'docker-compose', status: 'full' },
  { name: 'dotnet', description: '.NET CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'dotnet', status: 'full' },
  { name: 'drush', description: 'Drush aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'drush', status: 'full' },
  { name: 'eza', description: 'eza (modern ls) aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'eza', status: 'full' },
  { name: 'fabric', description: 'Fabric aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'fabric', status: 'full' },
  { name: 'flutter', description: 'Flutter aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'flutter', status: 'full' },
  { name: 'fluxcd', description: 'Flux CD aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'fluxcd', status: 'full' },
  { name: 'fnm', description: 'Fast Node Manager aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'fnm', status: 'full' },
  { name: 'gcloud', description: 'Google Cloud CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'gcloud', status: 'partial' },
  { name: 'gem', description: 'RubyGems aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'gem', status: 'full' },
  { name: 'gh', description: 'GitHub CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'gh', status: 'full' },
  { name: 'git-extras', description: 'Git extras aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'git-extras', status: 'full' },
  { name: 'git-flow', description: 'Git Flow aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'git-flow', status: 'full' },
  { name: 'git-lfs', description: 'Git LFS aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'git-lfs', status: 'full' },
  { name: 'gitignore', description: 'gitignore.io aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'gitignore', status: 'full' },
  { name: 'golang', description: 'Go language aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'golang', status: 'full' },
  { name: 'gradle', description: 'Gradle aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'gradle', status: 'full' },
  { name: 'grails', description: 'Grails aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'grails', status: 'full' },
  { name: 'grunt', description: 'Grunt aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'grunt', status: 'full' },
  { name: 'gulp', description: 'Gulp aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'gulp', status: 'full' },
  { name: 'hanami', description: 'Hanami aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'hanami', status: 'full' },
  { name: 'hasura', description: 'Hasura CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'hasura', status: 'full' },
  { name: 'hcloud', description: 'Hetzner Cloud CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'hcloud', status: 'full' },
  { name: 'helm', description: 'Helm aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'helm', status: 'full' },
  { name: 'heroku', description: 'Heroku aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'heroku', status: 'full' },
  { name: 'history', description: 'History aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'history', status: 'full' },
  { name: 'httpie', description: 'HTTPie aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'httpie', status: 'full' },
  { name: 'invoke', description: 'Invoke task runner aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'invoke', status: 'full' },
  { name: 'ionic', description: 'Ionic CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'ionic', status: 'full' },
  { name: 'jj', description: 'Jujutsu VCS aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'jj', status: 'full' },
  { name: 'jruby', description: 'JRuby aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'jruby', status: 'full' },
  { name: 'juju', description: 'Juju aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'juju', status: 'full' },
  { name: 'kate', description: 'Kate editor aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'kate', status: 'full' },
  { name: 'keychain', description: 'Keychain aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'keychain', status: 'full' },
  { name: 'kind', description: 'kind (Kubernetes in Docker) aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'kind', status: 'full' },
  { name: 'kn', description: 'Knative CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'kn', status: 'full' },
  { name: 'kompose', description: 'Kompose aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'kompose', status: 'full' },
  { name: 'kops', description: 'Kops aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'kops', status: 'full' },
  { name: 'kubectl', description: 'kubectl aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'kubectl', status: 'full' },
  { name: 'lando', description: 'Lando aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'lando', status: 'full' },
  { name: 'laravel', description: 'Laravel aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'laravel', status: 'full' },
  { name: 'laravel4', description: 'Laravel 4 aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'laravel4', status: 'full' },
  { name: 'laravel5', description: 'Laravel 5 aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'laravel5', status: 'full' },
  { name: 'lein', description: 'Leiningen aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'lein', status: 'full' },
  { name: 'lol', description: 'Fun command aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'lol', status: 'full' },
  { name: 'macports', description: 'MacPorts aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'macports', status: 'full', platform: 'macos' },
  { name: 'man', description: 'Man page aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'man', status: 'full' },
  { name: 'mercurial', description: 'Mercurial aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'mercurial', status: 'full' },
  { name: 'meteor', description: 'Meteor aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'meteor', status: 'full' },
  { name: 'microk8s', description: 'MicroK8s aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'microk8s', status: 'full' },
  { name: 'minikube', description: 'Minikube aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'minikube', status: 'full' },
  { name: 'mise', description: 'mise aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'mise', status: 'full' },
  { name: 'mix', description: 'Elixir Mix aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'mix', status: 'full' },
  { name: 'molecule', description: 'Ansible Molecule aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'molecule', status: 'full' },
  { name: 'mongocli', description: 'MongoDB CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'mongocli', status: 'full' },
  { name: 'mosh', description: 'Mosh aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'mosh', status: 'full' },
  { name: 'mvn', description: 'Maven aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'mvn', status: 'full' },
  { name: 'nanoc', description: 'Nanoc aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'nanoc', status: 'full' },
  { name: 'nats', description: 'NATS CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'nats', status: 'full' },
  { name: 'nestjs', description: 'NestJS CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'nestjs', status: 'full' },
  { name: 'ng', description: 'Angular CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'ng', status: 'full' },
  { name: 'ngrok', description: 'ngrok aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'ngrok', status: 'full' },
  { name: 'nmap', description: 'Nmap aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'nmap', status: 'full' },
  { name: 'node', description: 'Node.js aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'node', status: 'full' },
  { name: 'nodenv', description: 'nodenv aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'nodenv', status: 'full' },
  { name: 'npm', description: 'npm aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'npm', status: 'full' },
  { name: 'nvm', description: 'nvm aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'nvm', status: 'full' },
  { name: 'oc', description: 'OpenShift CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'oc', status: 'full' },
  { name: 'opentofu', description: 'OpenTofu aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'opentofu', status: 'full' },
  { name: 'operator-sdk', description: 'Operator SDK aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'operator-sdk', status: 'full' },
  { name: 'paver', description: 'Paver aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'paver', status: 'full' },
  { name: 'perl', description: 'Perl aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'perl', status: 'full' },
  { name: 'phing', description: 'Phing aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'phing', status: 'full' },
  { name: 'pip', description: 'pip aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'pip', status: 'full' },
  { name: 'pipenv', description: 'Pipenv aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'pipenv', status: 'full' },
  { name: 'pj', description: 'Project jump aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'pj', status: 'full' },
  { name: 'pm2', description: 'PM2 aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'pm2', status: 'full' },
  { name: 'podman', description: 'Podman aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'podman', status: 'full' },
  { name: 'poetry', description: 'Poetry aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'poetry', status: 'full' },
  { name: 'postgres', description: 'PostgreSQL aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'postgres', status: 'full' },
  { name: 'pre-commit', description: 'pre-commit aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'pre-commit', status: 'full' },
  { name: 'procs', description: 'procs aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'procs', status: 'full' },
  { name: 'pulumi', description: 'Pulumi aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'pulumi', status: 'full' },
  { name: 'pyenv', description: 'pyenv aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'pyenv', status: 'full' },
  { name: 'python', description: 'Python aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'python', status: 'full' },
  { name: 'rails', description: 'Ruby on Rails aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'rails', status: 'full' },
  { name: 'rake', description: 'Rake aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'rake', status: 'full' },
  { name: 'rbenv', description: 'rbenv aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'rbenv', status: 'full' },
  { name: 'rclone', description: 'rclone aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'rclone', status: 'full' },
  { name: 'react-native', description: 'React Native aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'react-native', status: 'full' },
  { name: 'redis-cli', description: 'Redis CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'redis-cli', status: 'full' },
  { name: 'rsync', description: 'rsync aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'rsync', status: 'full' },
  { name: 'ruby', description: 'Ruby aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'ruby', status: 'full' },
  { name: 'rust', description: 'Rust/Cargo aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'rust', status: 'full' },
  { name: 'rvm', description: 'RVM aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'rvm', status: 'full' },
  { name: 'salt', description: 'SaltStack aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'salt', status: 'full' },
  { name: 'scala', description: 'Scala aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'scala', status: 'full' },
  { name: 'scw', description: 'Scaleway CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'scw', status: 'full' },
  { name: 'sdk', description: 'SDKMAN aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'sdk', status: 'full' },
  { name: 'sfdx', description: 'Salesforce DX aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'sfdx', status: 'full' },
  { name: 'skaffold', description: 'Skaffold aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'skaffold', status: 'full' },
  { name: 'snap', description: 'Snap aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'snap', status: 'full', platform: 'linux' },
  { name: 'spring', description: 'Spring Boot aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'spring', status: 'full' },
  { name: 'stripe', description: 'Stripe CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'stripe', status: 'full' },
  { name: 'sublime', description: 'Sublime Text aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'sublime', status: 'full' },
  { name: 'svn', description: 'Subversion aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'svn', status: 'full' },
  { name: 'swiftpm', description: 'Swift Package Manager aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'swiftpm', status: 'full' },
  { name: 'symfony', description: 'Symfony aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'symfony', status: 'full' },
  { name: 'symfony2', description: 'Symfony 2 aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'symfony2', status: 'full' },
  { name: 'symfony6', description: 'Symfony 6 aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'symfony6', status: 'full' },
  { name: 'systemadmin', description: 'System admin aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'systemadmin', status: 'full' },
  { name: 'systemd', description: 'Systemd aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'systemd', status: 'full', platform: 'linux' },
  { name: 'tailscale', description: 'Tailscale aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'tailscale', status: 'full' },
  { name: 'task', description: 'Taskfile aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'task', status: 'full' },
  { name: 'taskwarrior', description: 'Taskwarrior aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'taskwarrior', status: 'full' },
  { name: 'terraform', description: 'Terraform aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'terraform', status: 'full' },
  { name: 'tig', description: 'Tig aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'tig', status: 'full' },
  { name: 'timoni', description: 'Timoni aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'timoni', status: 'full' },
  { name: 'tldr', description: 'tldr aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'tldr', status: 'full' },
  { name: 'tmux', description: 'tmux aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'tmux', status: 'full' },
  { name: 'tmuxinator', description: 'Tmuxinator aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'tmuxinator', status: 'full' },
  { name: 'uv', description: 'uv Python package manager aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'uv', status: 'full' },
  { name: 'vagrant', description: 'Vagrant aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'vagrant', status: 'full' },
  { name: 'vault', description: 'HashiCorp Vault aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'vault', status: 'full' },
  { name: 'volta', description: 'Volta aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'volta', status: 'full' },
  { name: 'vscode', description: 'VS Code aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'vscode', status: 'full' },
  { name: 'wp-cli', description: 'WP-CLI aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'wp-cli', status: 'full' },
  { name: 'xcode', description: 'Xcode aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'xcode', status: 'full', platform: 'macos' },
  { name: 'yarn', description: 'Yarn aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'yarn', status: 'full' },
  { name: 'yum', description: 'Yum aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'yum', status: 'full', platform: 'linux' },
  { name: 'zoxide', description: 'Zoxide aliases (ported from oh-my-zsh)', category: 'alias', omzName: 'zoxide', status: 'full' },

  // ── Partial ports (alias subset only) ─────────────────────────────
  { name: 'brew', description: 'Homebrew aliases (macOS only, partial)', category: 'alias', omzName: 'brew', status: 'partial', platform: 'macos' },
  { name: 'macos', description: 'macOS utility aliases (partial)', category: 'alias', omzName: 'macos', status: 'partial', platform: 'macos' },
  { name: 'ubuntu', description: 'Ubuntu aliases (partial)', category: 'alias', omzName: 'ubuntu', status: 'partial', platform: 'linux' },
  { name: 'archlinux', description: 'Arch Linux aliases (partial)', category: 'alias', omzName: 'archlinux', status: 'partial', platform: 'linux' },
  { name: 'suse', description: 'openSUSE aliases (partial)', category: 'alias', omzName: 'suse', status: 'partial', platform: 'linux' },

  // ── Hook plugins (Phase 12 hand-written, planned) ─────────────────
  { name: 'colored-man-pages', description: 'Colorize man page output', category: 'hook', omzName: 'colored-man-pages', status: 'full' },
  { name: 'timer', description: 'Show command execution time', category: 'hook', omzName: 'timer', status: 'full' },
  { name: 'per-directory-history', description: 'Per-directory command history', category: 'hook', omzName: 'per-directory-history', status: 'full' },
  { name: 'dirpersist', description: 'Save and restore directory stack', category: 'hook', omzName: 'dirpersist', status: 'full' },
  { name: 'last-working-dir', description: 'Remember last working directory', category: 'hook', omzName: 'last-working-dir', status: 'full' },
  { name: 'bgnotify', description: 'Desktop notification for long commands', category: 'hook', omzName: 'bgnotify', status: 'full' },
  { name: 'dotenv', description: 'Auto-source .env files on cd', category: 'hook', omzName: 'dotenv', status: 'full' },
  { name: 'magic-enter', description: 'Run git status + ls on empty enter', category: 'hook', omzName: 'magic-enter', status: 'full' },
  { name: 'python-venv', description: 'Auto-activate Python virtualenv', category: 'hook', omzName: 'virtualenv', status: 'full' },
  { name: 'poetry-env', description: 'Auto-activate Poetry virtualenv', category: 'hook', omzName: 'poetry', status: 'full' },
  { name: 'pipenv-env', description: 'Auto-activate Pipenv shell', category: 'hook', omzName: 'pipenv', status: 'full' },
  { name: 'nvm-auto', description: 'Auto-switch Node version via .nvmrc', category: 'hook', omzName: 'nvm', status: 'full' },
  { name: 'zbell', description: 'Terminal bell for long commands', category: 'hook', omzName: 'zbell', status: 'full' },
  { name: 'globalias', description: 'Expand aliases before execution', category: 'hook', omzName: 'globalias', status: 'full' },
  { name: 'safe-paste', description: 'Prevent execution of pasted multi-line commands', category: 'hook', omzName: 'safe-paste', status: 'full' },
  { name: 'copybuffer', description: 'Copy current buffer to clipboard', category: 'hook', omzName: 'copybuffer', status: 'full' },
  { name: 'dircycle', description: 'Cycle directory history with Alt+arrows', category: 'hook', omzName: 'dircycle', status: 'full' },
  { name: 'thefuck', description: 'Corrects previous console command', category: 'hook', omzName: 'thefuck', status: 'full' },

  // ── Completion plugins (already covered by Phase 9 umbrella plugins) ──
  { name: 'docker-completion', description: 'Docker completions (covered by docker-completions)', category: 'completion', omzName: 'docker', status: 'full' },
  { name: 'kubectl-completion', description: 'kubectl completions (covered by kubectl-completions)', category: 'completion', omzName: 'kubectl', status: 'full' },
  { name: 'npm-completion', description: 'npm completions (covered by npm-completions)', category: 'completion', omzName: 'npm', status: 'full' },
  { name: 'pip-completion', description: 'pip completions (covered by devtools-completions)', category: 'completion', omzName: 'pip', status: 'full' },
  { name: 'yarn-completion', description: 'yarn completions (covered by devtools-completions)', category: 'completion', omzName: 'yarn', status: 'full' },
  { name: 'cargo-completion', description: 'cargo completions (covered by devtools-completions)', category: 'completion', omzName: 'cargo', status: 'full' },
  { name: 'terraform-completion', description: 'terraform completions (covered by cloud-completions)', category: 'completion', omzName: 'terraform', status: 'full' },
  { name: 'helm-completion', description: 'helm completions (covered by cloud-completions)', category: 'completion', omzName: 'helm', status: 'full' },
  { name: 'aws-completion', description: 'AWS CLI completions (covered by cloud-completions)', category: 'completion', omzName: 'aws', status: 'full' },
  { name: 'gcloud-completion', description: 'gcloud completions (covered by cloud-completions)', category: 'completion', omzName: 'gcloud', status: 'full' },
  { name: 'az-completion', description: 'Azure CLI completions (covered by cloud-completions)', category: 'completion', omzName: 'azure-cli', status: 'full' },
  { name: 'ssh-completion', description: 'SSH completions (covered by sysadmin-completions)', category: 'completion', omzName: 'ssh', status: 'full' },
  { name: 'systemctl-completion', description: 'systemctl completions (covered by sysadmin-completions)', category: 'completion', omzName: 'systemd', status: 'full' },
  { name: 'tmux-completion', description: 'tmux completions (covered by sysadmin-completions)', category: 'completion', omzName: 'tmux', status: 'full' },

  // ── No-equivalent plugins (zsh-only or binary integrations) ───────
  { name: 'fzf', description: 'Fuzzy finder (requires native binary)', category: 'utility', omzName: 'fzf', status: 'no-equivalent' },
  { name: 'fasd', description: 'Quick access to files/dirs (requires native binary)', category: 'utility', omzName: 'fasd', status: 'no-equivalent' },
  { name: 'z', description: 'Directory jump (requires native binary)', category: 'utility', omzName: 'z', status: 'no-equivalent' },
  { name: 'autojump', description: 'Directory jump (requires native binary)', category: 'utility', omzName: 'autojump', status: 'no-equivalent' },
  { name: 'vi-mode', description: 'Vi keybindings for zsh (zsh-only)', category: 'utility', omzName: 'vi-mode', status: 'no-equivalent' },
  { name: 'history-substring-search', description: 'History substring search (zsh-only)', category: 'utility', omzName: 'history-substring-search', status: 'no-equivalent' },
  { name: 'zsh-interactive-cd', description: 'Interactive cd (zsh-only)', category: 'utility', omzName: 'zsh-interactive-cd', status: 'no-equivalent' },
  { name: 'zsh-navigation-tools', description: 'Navigation tools (zsh-only)', category: 'utility', omzName: 'zsh-navigation-tools', status: 'no-equivalent' },
  { name: 'zsh-autosuggestions', description: 'Auto-suggestions (natively implemented in Nesh)', category: 'utility', omzName: 'zsh-autosuggestions', status: 'no-equivalent' },
  { name: 'zsh-syntax-highlighting', description: 'Syntax highlighting (natively implemented in Nesh)', category: 'utility', omzName: 'zsh-syntax-highlighting', status: 'no-equivalent' },
  { name: 'otp', description: 'One-time password (security daemon)', category: 'utility', omzName: 'otp', status: 'no-equivalent' },
  { name: 'gpg-agent', description: 'GPG agent management (shell-level only)', category: 'utility', omzName: 'gpg-agent', status: 'no-equivalent' },
  { name: 'ssh-agent', description: 'SSH agent management (shell-level only)', category: 'utility', omzName: 'ssh-agent', status: 'no-equivalent' },
  { name: 'iterm2', description: 'iTerm2 integration (terminal emulator specific)', category: 'utility', omzName: 'iterm2', status: 'no-equivalent' },
  { name: 'term-tab', description: 'Terminal tab naming (terminal emulator specific)', category: 'utility', omzName: 'term_tab', status: 'no-equivalent' },
  { name: 'kitty', description: 'Kitty terminal integration (terminal emulator specific)', category: 'utility', omzName: 'kitty', status: 'no-equivalent' },
  { name: 'conda', description: 'Conda env management (requires shell functions)', category: 'utility', omzName: 'conda', status: 'no-equivalent' },
  { name: 'conda-env', description: 'Conda environment (requires shell functions)', category: 'utility', omzName: 'conda-env', status: 'no-equivalent' },
  { name: 'chruby', description: 'chruby version manager (requires shell functions)', category: 'utility', omzName: 'chruby', status: 'no-equivalent' },
  { name: 'jenv', description: 'jenv version manager (requires shell functions)', category: 'utility', omzName: 'jenv', status: 'no-equivalent' },
  { name: 'asdf', description: 'asdf version manager (requires shell functions)', category: 'utility', omzName: 'asdf', status: 'no-equivalent' },
  { name: 'compleat', description: 'Compleat completion system (zsh-specific)', category: 'utility', omzName: 'compleat', status: 'no-equivalent' },
  { name: 'colemak', description: 'Colemak keyboard layout (zsh-specific)', category: 'utility', omzName: 'colemak', status: 'no-equivalent' },
  { name: 'kube-ps1', description: 'Kubernetes prompt segment (use segment API instead)', category: 'utility', omzName: 'kube-ps1', status: 'no-equivalent' },
  { name: 'vagrant-prompt', description: 'Vagrant prompt segment (use segment API instead)', category: 'utility', omzName: 'vagrant-prompt', status: 'no-equivalent' },
  { name: 'git-prompt', description: 'Git prompt segment (use segment API instead)', category: 'utility', omzName: 'git-prompt', status: 'no-equivalent' },
  { name: 'virtualenvwrapper', description: 'virtualenvwrapper (requires shell functions)', category: 'utility', omzName: 'virtualenvwrapper', status: 'no-equivalent' },
  { name: 'emacs', description: 'Emacs keybindings (zsh-only)', category: 'utility', omzName: 'emacs', status: 'no-equivalent' },
  { name: 'screen', description: 'GNU Screen integration (requires shell functions)', category: 'utility', omzName: 'screen', status: 'no-equivalent' },
  { name: 'profiles', description: 'Shell profiles (zsh-specific)', category: 'utility', omzName: 'profiles', status: 'no-equivalent' },
  { name: 'colored-man-pages-zsh', description: 'Colored man pages (zsh-specific termcap)', category: 'utility', omzName: 'colored-man-pages', status: 'no-equivalent' },
  { name: 'emoji', description: 'Emoji plugin (zsh-specific)', category: 'utility', omzName: 'emoji', status: 'no-equivalent' },
  { name: 'emoji-clock', description: 'Emoji clock (zsh-specific)', category: 'utility', omzName: 'emoji-clock', status: 'no-equivalent' },
  { name: 'emotty', description: 'Emotty (zsh-specific)', category: 'utility', omzName: 'emotty', status: 'no-equivalent' },
  { name: 'frontend-search', description: 'Frontend search (web-search covers this)', category: 'utility', omzName: 'frontend-search', status: 'no-equivalent' },
  { name: 'genpass', description: 'Password generator (requires shell functions)', category: 'utility', omzName: 'genpass', status: 'no-equivalent' },
  { name: 'hitchhiker', description: 'Hitchhiker guide quotes (novelty)', category: 'utility', omzName: 'hitchhiker', status: 'no-equivalent' },
  { name: 'jump', description: 'Jump between directories (requires shell functions)', category: 'utility', omzName: 'jump', status: 'no-equivalent' },
  { name: 'marked2', description: 'Marked 2 app integration (macOS-specific)', category: 'utility', omzName: 'marked2', status: 'no-equivalent' },
  { name: 'nyan', description: 'Nyan cat (novelty)', category: 'utility', omzName: 'nyan', status: 'no-equivalent' },
  { name: 'rand-quote', description: 'Random quotes (novelty)', category: 'utility', omzName: 'rand-quote', status: 'no-equivalent' },
  { name: 'themes', description: 'OMZ theme switcher (replaced by Nesh templates)', category: 'utility', omzName: 'themes', status: 'no-equivalent' },
  { name: 'torrent', description: 'Torrent aliases (niche)', category: 'utility', omzName: 'torrent', status: 'no-equivalent' },
  { name: 'transfer', description: 'transfer.sh uploads (requires curl functions)', category: 'utility', omzName: 'transfer', status: 'no-equivalent' },
  { name: 'universalarchive', description: 'Archive creation (extract covers this)', category: 'utility', omzName: 'universalarchive', status: 'no-equivalent' },
  { name: 'wd', description: 'Warp directory (requires shell functions)', category: 'utility', omzName: 'wd', status: 'no-equivalent' },
  { name: 'web-search-zsh', description: 'Web search (web-search already covers this)', category: 'utility', omzName: 'web-search', status: 'no-equivalent' },
  { name: 'zsh-reload', description: 'Reload zsh config (zsh-specific)', category: 'utility', omzName: 'zsh_reload', status: 'no-equivalent' },
  { name: 'globalias-zsh', description: 'Global alias expansion (zsh-specific)', category: 'utility', omzName: 'globalias', status: 'no-equivalent' },
  { name: 'magic-enter-zsh', description: 'Magic enter (zsh-specific)', category: 'utility', omzName: 'magic-enter', status: 'no-equivalent' },
  { name: 'alias-finder', description: 'Find which alias matches a command (zsh-specific)', category: 'utility', omzName: 'alias-finder', status: 'no-equivalent' },
  { name: 'aliases', description: 'List all aliases (zsh-specific)', category: 'utility', omzName: 'aliases', status: 'no-equivalent' },
  { name: 'autopep8', description: 'autopep8 aliases (too niche)', category: 'utility', omzName: 'autopep8', status: 'no-equivalent' },
  { name: 'battery', description: 'Battery status (requires platform-specific binary)', category: 'utility', omzName: 'battery', status: 'no-equivalent' },
  { name: 'bgnotify-zsh', description: 'Background notify (zsh-specific)', category: 'utility', omzName: 'bgnotify', status: 'no-equivalent' },
  { name: 'branch', description: 'Git branch in prompt (use segment API)', category: 'utility', omzName: 'branch', status: 'no-equivalent' },
  { name: 'catimg', description: 'Display images in terminal (requires external tool)', category: 'utility', omzName: 'catimg', status: 'no-equivalent' },
  { name: 'chucknorris', description: 'Chuck Norris jokes (novelty)', category: 'utility', omzName: 'chucknorris', status: 'no-equivalent' },
  { name: 'coffee', description: 'CoffeeScript aliases (deprecated language)', category: 'utility', omzName: 'coffee', status: 'no-equivalent' },
  { name: 'colorize', description: 'Syntax highlighting for cat (requires pygments)', category: 'utility', omzName: 'colorize', status: 'no-equivalent' },
  { name: 'command-not-found', description: 'Package suggestion for unknown commands (OS-specific)', category: 'utility', omzName: 'command-not-found', status: 'no-equivalent' },
  { name: 'copybuffer-zsh', description: 'Copy buffer (zsh-specific ZLE)', category: 'utility', omzName: 'copybuffer', status: 'no-equivalent' },
  { name: 'copyfile', description: 'Copy file to clipboard (requires pbcopy/xclip)', category: 'utility', omzName: 'copyfile', status: 'no-equivalent' },
  { name: 'cp', description: 'cp with progress bar (requires rsync)', category: 'utility', omzName: 'cp', status: 'no-equivalent' },
  { name: 'dash', description: 'Dash documentation (macOS-specific)', category: 'utility', omzName: 'dash', status: 'no-equivalent' },
  { name: 'dircycle-zsh', description: 'Directory cycle (zsh-specific ZLE)', category: 'utility', omzName: 'dircycle', status: 'no-equivalent' },
  { name: 'direnv', description: 'direnv integration (requires native binary)', category: 'utility', omzName: 'direnv', status: 'no-equivalent' },
  { name: 'dnf', description: 'DNF package manager (Fedora-specific)', category: 'utility', omzName: 'dnf', status: 'no-equivalent' },
  { name: 'docker-machine', description: 'Docker Machine (deprecated)', category: 'utility', omzName: 'docker-machine', status: 'no-equivalent' },
  { name: 'dotenv-zsh', description: 'Dotenv (zsh-specific hook)', category: 'utility', omzName: 'dotenv', status: 'no-equivalent' },
  { name: 'fancy-ctrl-z', description: 'Fancy Ctrl-Z (zsh-specific ZLE)', category: 'utility', omzName: 'fancy-ctrl-z', status: 'no-equivalent' },
  { name: 'fig', description: 'Fig integration (deprecated service)', category: 'utility', omzName: 'fig', status: 'no-equivalent' },
  { name: 'fossil', description: 'Fossil VCS (too niche)', category: 'utility', omzName: 'fossil', status: 'no-equivalent' },
  { name: 'gas', description: 'Gas (too niche)', category: 'utility', omzName: 'gas', status: 'no-equivalent' },
  { name: 'gitfast', description: 'Fast git completions (zsh-specific)', category: 'utility', omzName: 'gitfast', status: 'no-equivalent' },
  { name: 'gnu-utils', description: 'GNU utilities (requires coreutils)', category: 'utility', omzName: 'gnu-utils', status: 'no-equivalent' },
]

// ── Alias plugin data for batch generation ──────────────────────────

export const ALIAS_PLUGIN_DATA: Readonly<Record<string, { readonly description: string; readonly aliases: Readonly<Record<string, string>> }>> = {
  ansible: {
    description: 'Ansible aliases (ported from oh-my-zsh)',
    aliases: {
      a: 'ansible',
      ap: 'ansible-playbook',
      avc: 'ansible-vault create',
      ave: 'ansible-vault edit',
      avr: 'ansible-vault rekey',
      avd: 'ansible-vault decrypt',
      avv: 'ansible-vault view',
      aga: 'ansible-galaxy',
      agad: 'ansible-galaxy delete',
      agai: 'ansible-galaxy install',
      agal: 'ansible-galaxy list',
      agas: 'ansible-galaxy search',
    },
  },
  arcanist: {
    description: 'Arcanist aliases (ported from oh-my-zsh)',
    aliases: {
      ad: 'arc diff',
      adp: 'arc diff --preview',
      al: 'arc land',
      ab: 'arc branch',
    },
  },
  argocd: {
    description: 'Argo CD aliases (ported from oh-my-zsh)',
    aliases: {
      argocd: 'argocd',
      argc: 'argocd cluster',
      argcl: 'argocd cluster list',
      arga: 'argocd app',
      argal: 'argocd app list',
      argas: 'argocd app sync',
      argag: 'argocd app get',
      argad: 'argocd app delete',
      argp: 'argocd proj',
      argpl: 'argocd proj list',
    },
  },
  aws: {
    description: 'AWS CLI aliases (ported from oh-my-zsh)',
    aliases: {
      awsl: 'aws configure list',
      awsp: 'aws configure list-profiles',
      awss3: 'aws s3',
      awss3ls: 'aws s3 ls',
      awsec2: 'aws ec2 describe-instances',
      awslogs: 'aws logs',
      awseks: 'aws eks',
      awsiam: 'aws iam',
      awslambda: 'aws lambda',
      awscf: 'aws cloudformation',
    },
  },
  azure: {
    description: 'Azure CLI aliases (ported from oh-my-zsh)',
    aliases: {
      az: 'az',
      azl: 'az login',
      azacc: 'az account',
      azaccl: 'az account list',
      azaccs: 'az account set',
      azvm: 'az vm',
      azvml: 'az vm list',
      azaks: 'az aks',
      azaksl: 'az aks list',
      azg: 'az group',
      azgl: 'az group list',
    },
  },
  bazel: {
    description: 'Bazel aliases (ported from oh-my-zsh)',
    aliases: {
      bzb: 'bazel build',
      bzt: 'bazel test',
      bzr: 'bazel run',
      bzq: 'bazel query',
      bzc: 'bazel clean',
      bzf: 'bazel fetch',
    },
  },
  bun: {
    description: 'Bun runtime aliases (ported from oh-my-zsh)',
    aliases: {
      bi: 'bun install',
      ba: 'bun add',
      bad: 'bun add -d',
      brm: 'bun remove',
      br: 'bun run',
      brd: 'bun run dev',
      brb: 'bun run build',
      brt: 'bun run test',
      bx: 'bunx',
    },
  },
  bundler: {
    description: 'Ruby Bundler aliases (ported from oh-my-zsh)',
    aliases: {
      be: 'bundle exec',
      bl: 'bundle list',
      bi: 'bundle install',
      bu: 'bundle update',
      bo: 'bundle open',
      bp: 'bundle pack',
      bout: 'bundle outdated',
    },
  },
  capistrano: {
    description: 'Capistrano aliases (ported from oh-my-zsh)',
    aliases: {
      cap: 'bundle exec cap',
      capd: 'bundle exec cap deploy',
    },
  },
  chezmoi: {
    description: 'Chezmoi dotfile manager aliases (ported from oh-my-zsh)',
    aliases: {
      cz: 'chezmoi',
      cza: 'chezmoi add',
      cze: 'chezmoi edit',
      czd: 'chezmoi diff',
      czu: 'chezmoi update',
      czap: 'chezmoi apply',
      czcd: 'chezmoi cd',
    },
  },
  cloudfoundry: {
    description: 'Cloud Foundry aliases (ported from oh-my-zsh)',
    aliases: {
      cf: 'cf',
      cfa: 'cf apps',
      cfs: 'cf services',
      cfp: 'cf push',
      cfl: 'cf logs',
      cfd: 'cf delete',
      cfr: 'cf restage',
      cfsc: 'cf scale',
    },
  },
  'common-aliases': {
    description: 'Common shell aliases (portable subset)',
    aliases: {
      l: 'ls -lah',
      la: 'ls -lAh',
      ll: 'ls -lh',
      lsa: 'ls -lah',
      md: 'mkdir -p',
      rd: 'rmdir',
      '..' : 'cd ..',
      '...': 'cd ../..',
      '....': 'cd ../../..',
      '.....': 'cd ../../../..',
      H: 'head',
      T: 'tail',
      G: 'grep',
    },
  },
  composer: {
    description: 'PHP Composer aliases (ported from oh-my-zsh)',
    aliases: {
      c: 'composer',
      ci: 'composer install',
      cu: 'composer update',
      cr: 'composer require',
      crd: 'composer require --dev',
      ccp: 'composer create-project',
      cdu: 'composer dump-autoload',
      cg: 'composer global',
      cgi: 'composer global install',
      cgu: 'composer global update',
    },
  },
  dbt: {
    description: 'dbt aliases (ported from oh-my-zsh)',
    aliases: {
      dbtr: 'dbt run',
      dbtt: 'dbt test',
      dbtb: 'dbt build',
      dbtd: 'dbt docs',
      dbtdg: 'dbt docs generate',
      dbtds: 'dbt docs serve',
      dbts: 'dbt seed',
    },
  },
  debian: {
    description: 'Debian/apt aliases (ported from oh-my-zsh)',
    aliases: {
      agi: 'sudo apt-get install',
      agr: 'sudo apt-get remove',
      agu: 'sudo apt-get update',
      agug: 'sudo apt-get upgrade',
      acs: 'apt-cache search',
      agud: 'sudo apt-get dist-upgrade',
      agp: 'sudo apt-get purge',
      agar: 'sudo apt-get autoremove',
    },
  },
  deno: {
    description: 'Deno aliases (ported from oh-my-zsh)',
    aliases: {
      de: 'deno',
      der: 'deno run',
      det: 'deno test',
      deb: 'deno bench',
      def: 'deno fmt',
      del: 'deno lint',
      dec: 'deno compile',
      dei: 'deno install',
    },
  },
  'docker-compose': {
    description: 'Docker Compose aliases (ported from oh-my-zsh)',
    aliases: {
      dco: 'docker compose',
      dcb: 'docker compose build',
      dce: 'docker compose exec',
      dcps: 'docker compose ps',
      dcr: 'docker compose run',
      dcstop: 'docker compose stop',
      dcup: 'docker compose up',
      dcupb: 'docker compose up --build',
      dcupd: 'docker compose up -d',
      dcdn: 'docker compose down',
      dcl: 'docker compose logs',
      dclf: 'docker compose logs -f',
      dcpull: 'docker compose pull',
      dcrestart: 'docker compose restart',
      dcrm: 'docker compose rm',
    },
  },
  dotnet: {
    description: '.NET CLI aliases (ported from oh-my-zsh)',
    aliases: {
      dn: 'dotnet',
      dnr: 'dotnet run',
      dnb: 'dotnet build',
      dnt: 'dotnet test',
      dna: 'dotnet add',
      dnap: 'dotnet add package',
      dnnew: 'dotnet new',
      dnres: 'dotnet restore',
      dnp: 'dotnet publish',
    },
  },
  drush: {
    description: 'Drush aliases (ported from oh-my-zsh)',
    aliases: {
      dr: 'drush',
      drc: 'drush cr',
      drs: 'drush status',
      drul: 'drush uli',
      dren: 'drush en',
      drpm: 'drush pml',
    },
  },
  eza: {
    description: 'eza (modern ls) aliases (ported from oh-my-zsh)',
    aliases: {
      ls: 'eza',
      l: 'eza -lah',
      la: 'eza -lah',
      ll: 'eza -lh',
      lt: 'eza --tree',
      lt2: 'eza --tree --level=2',
      lt3: 'eza --tree --level=3',
      lg: 'eza -lah --git',
    },
  },
  fabric: {
    description: 'Fabric aliases (ported from oh-my-zsh)',
    aliases: {
      fab: 'fabric',
      fabr: 'fabric run',
      fabp: 'fabric put',
      fabg: 'fabric get',
    },
  },
  flutter: {
    description: 'Flutter aliases (ported from oh-my-zsh)',
    aliases: {
      fl: 'flutter',
      flr: 'flutter run',
      flb: 'flutter build',
      flt: 'flutter test',
      flc: 'flutter clean',
      flpg: 'flutter pub get',
      flpa: 'flutter pub add',
      fld: 'flutter doctor',
      flan: 'flutter analyze',
    },
  },
  fluxcd: {
    description: 'Flux CD aliases (ported from oh-my-zsh)',
    aliases: {
      flx: 'flux',
      flxr: 'flux reconcile',
      flxg: 'flux get',
      flxga: 'flux get all',
      flxs: 'flux suspend',
      flxrs: 'flux resume',
    },
  },
  fnm: {
    description: 'Fast Node Manager aliases (ported from oh-my-zsh)',
    aliases: {
      fnmi: 'fnm install',
      fnmu: 'fnm use',
      fnml: 'fnm list',
      fnmlr: 'fnm list-remote',
      fnmd: 'fnm default',
      fnmc: 'fnm current',
    },
  },
  gcloud: {
    description: 'Google Cloud CLI aliases (ported from oh-my-zsh)',
    aliases: {
      gcc: 'gcloud config',
      gccl: 'gcloud config list',
      gccs: 'gcloud config set',
      gcce: 'gcloud compute',
      gcci: 'gcloud compute instances',
      gccil: 'gcloud compute instances list',
      gcl: 'gcloud container clusters list',
      gcp: 'gcloud projects list',
    },
  },
  gem: {
    description: 'RubyGems aliases (ported from oh-my-zsh)',
    aliases: {
      gei: 'gem install',
      geu: 'gem update',
      gel: 'gem list',
      ges: 'gem search',
      geui: 'gem uninstall',
    },
  },
  gh: {
    description: 'GitHub CLI aliases (ported from oh-my-zsh)',
    aliases: {
      ghpr: 'gh pr',
      ghprc: 'gh pr create',
      ghprl: 'gh pr list',
      ghprv: 'gh pr view',
      ghprco: 'gh pr checkout',
      ghi: 'gh issue',
      ghic: 'gh issue create',
      ghil: 'gh issue list',
      ghiv: 'gh issue view',
      ghr: 'gh repo',
      ghrc: 'gh repo clone',
      ghrv: 'gh repo view',
    },
  },
  'git-extras': {
    description: 'Git extras aliases (ported from oh-my-zsh)',
    aliases: {
      gcount: 'git shortlog --summary --numbered',
      ginfo: 'git summary',
      gauthors: 'git authors',
      gef: 'git effort',
      gign: 'git ignore',
    },
  },
  'git-flow': {
    description: 'Git Flow aliases (ported from oh-my-zsh)',
    aliases: {
      gfi: 'git flow init',
      gff: 'git flow feature',
      gffs: 'git flow feature start',
      gfff: 'git flow feature finish',
      gfr: 'git flow release',
      gfrs: 'git flow release start',
      gfrf: 'git flow release finish',
      gfh: 'git flow hotfix',
      gfhs: 'git flow hotfix start',
      gfhf: 'git flow hotfix finish',
    },
  },
  'git-lfs': {
    description: 'Git LFS aliases (ported from oh-my-zsh)',
    aliases: {
      glfsi: 'git lfs install',
      glfst: 'git lfs track',
      glfsls: 'git lfs ls-files',
      glfsp: 'git lfs push',
      glfspl: 'git lfs pull',
    },
  },
  gitignore: {
    description: 'gitignore.io aliases (ported from oh-my-zsh)',
    aliases: {
      gi: 'curl -sL https://www.toptal.com/developers/gitignore/api/',
    },
  },
  golang: {
    description: 'Go language aliases (ported from oh-my-zsh)',
    aliases: {
      gob: 'go build',
      goc: 'go clean',
      god: 'go doc',
      gof: 'go fmt',
      gog: 'go get',
      goi: 'go install',
      gol: 'go list',
      gom: 'go mod',
      gomt: 'go mod tidy',
      gor: 'go run',
      got: 'go test',
      gov: 'go vet',
    },
  },
  gradle: {
    description: 'Gradle aliases (ported from oh-my-zsh)',
    aliases: {
      gw: './gradlew',
      gwb: './gradlew build',
      gwc: './gradlew clean',
      gwt: './gradlew test',
      gwr: './gradlew run',
      gwcb: './gradlew clean build',
    },
  },
  grails: {
    description: 'Grails aliases (ported from oh-my-zsh)',
    aliases: {
      gra: 'grails',
      grra: 'grails run-app',
      grta: 'grails test-app',
    },
  },
  grunt: {
    description: 'Grunt aliases (ported from oh-my-zsh)',
    aliases: {
      gr: 'grunt',
      grd: 'grunt --debug',
    },
  },
  gulp: {
    description: 'Gulp aliases (ported from oh-my-zsh)',
    aliases: {
      gu: 'gulp',
      gub: 'gulp build',
      gut: 'gulp test',
      guc: 'gulp clean',
    },
  },
  hanami: {
    description: 'Hanami aliases (ported from oh-my-zsh)',
    aliases: {
      hn: 'hanami',
      hns: 'hanami server',
      hnc: 'hanami console',
      hng: 'hanami generate',
      hnr: 'hanami routes',
    },
  },
  hasura: {
    description: 'Hasura CLI aliases (ported from oh-my-zsh)',
    aliases: {
      hsc: 'hasura console',
      hsm: 'hasura migrate',
      hsms: 'hasura migrate status',
      hsma: 'hasura migrate apply',
      hss: 'hasura seed',
      hsmd: 'hasura metadata',
      hsmde: 'hasura metadata export',
      hsmda: 'hasura metadata apply',
    },
  },
  hcloud: {
    description: 'Hetzner Cloud CLI aliases (ported from oh-my-zsh)',
    aliases: {
      hc: 'hcloud',
      hcs: 'hcloud server',
      hcsl: 'hcloud server list',
      hcsc: 'hcloud server create',
      hcsd: 'hcloud server delete',
      hcn: 'hcloud network',
      hcnl: 'hcloud network list',
    },
  },
  helm: {
    description: 'Helm aliases (ported from oh-my-zsh)',
    aliases: {
      h: 'helm',
      hi: 'helm install',
      hu: 'helm upgrade',
      hun: 'helm uninstall',
      hl: 'helm list',
      hs: 'helm search',
      hsr: 'helm search repo',
      hsh: 'helm search hub',
      hrr: 'helm repo remove',
      hra: 'helm repo add',
      hru: 'helm repo update',
      hrl: 'helm repo list',
      ht: 'helm template',
      hv: 'helm version',
    },
  },
  heroku: {
    description: 'Heroku aliases (ported from oh-my-zsh)',
    aliases: {
      hk: 'heroku',
      hka: 'heroku apps',
      hkal: 'heroku apps:list',
      hkl: 'heroku logs',
      hklt: 'heroku logs --tail',
      hkr: 'heroku run',
      hkrc: 'heroku run console',
      hkp: 'heroku ps',
      hkc: 'heroku config',
    },
  },
  history: {
    description: 'History aliases (ported from oh-my-zsh)',
    aliases: {
      h: 'history',
      hs: 'history | grep',
      hsi: 'history | grep -i',
    },
  },
  httpie: {
    description: 'HTTPie aliases (ported from oh-my-zsh)',
    aliases: {
      https: 'http --default-scheme=https',
      httpd: 'http --download',
    },
  },
  invoke: {
    description: 'Invoke task runner aliases (ported from oh-my-zsh)',
    aliases: {
      inv: 'invoke',
      invl: 'invoke --list',
    },
  },
  ionic: {
    description: 'Ionic CLI aliases (ported from oh-my-zsh)',
    aliases: {
      ion: 'ionic',
      ions: 'ionic serve',
      ionb: 'ionic build',
      iong: 'ionic generate',
    },
  },
  jj: {
    description: 'Jujutsu VCS aliases (ported from oh-my-zsh)',
    aliases: {
      jjd: 'jj diff',
      jjl: 'jj log',
      jjs: 'jj status',
      jjn: 'jj new',
      jje: 'jj edit',
      jjds: 'jj describe',
      jjgp: 'jj git push',
      jjgf: 'jj git fetch',
    },
  },
  jruby: {
    description: 'JRuby aliases (ported from oh-my-zsh)',
    aliases: {
      jr: 'jruby',
      jri: 'jruby -S irb',
      jrg: 'jruby -S gem',
    },
  },
  juju: {
    description: 'Juju aliases (ported from oh-my-zsh)',
    aliases: {
      jd: 'juju deploy',
      js: 'juju status',
      jss: 'juju switch',
      jm: 'juju models',
    },
  },
  kate: {
    description: 'Kate editor aliases (ported from oh-my-zsh)',
    aliases: {
      kt: 'kate',
      ktn: 'kate --new',
    },
  },
  keychain: {
    description: 'Keychain aliases (ported from oh-my-zsh)',
    aliases: {
      kc: 'keychain',
      kcl: 'keychain --list',
    },
  },
  kind: {
    description: 'kind (Kubernetes in Docker) aliases (ported from oh-my-zsh)',
    aliases: {
      kdc: 'kind create cluster',
      kdd: 'kind delete cluster',
      kdg: 'kind get clusters',
      kdl: 'kind load docker-image',
    },
  },
  kn: {
    description: 'Knative CLI aliases (ported from oh-my-zsh)',
    aliases: {
      kns: 'kn service',
      knsl: 'kn service list',
      knsc: 'kn service create',
      knsd: 'kn service delete',
      knsu: 'kn service update',
      knr: 'kn revision',
      knrl: 'kn revision list',
    },
  },
  kompose: {
    description: 'Kompose aliases (ported from oh-my-zsh)',
    aliases: {
      kc: 'kompose convert',
      ku: 'kompose up',
      kd: 'kompose down',
    },
  },
  kops: {
    description: 'Kops aliases (ported from oh-my-zsh)',
    aliases: {
      kpsc: 'kops create cluster',
      kpsd: 'kops delete cluster',
      kpsu: 'kops update cluster',
      kpsv: 'kops validate cluster',
      kpsg: 'kops get',
      kpse: 'kops edit',
    },
  },
  kubectl: {
    description: 'kubectl aliases (ported from oh-my-zsh)',
    aliases: {
      k: 'kubectl',
      kaf: 'kubectl apply -f',
      kgp: 'kubectl get pods',
      kgs: 'kubectl get svc',
      kgd: 'kubectl get deployments',
      kdp: 'kubectl describe pod',
      kds: 'kubectl describe svc',
      kdd: 'kubectl describe deployment',
      kl: 'kubectl logs',
      klf: 'kubectl logs -f',
      kex: 'kubectl exec -it',
      kd: 'kubectl delete',
      kdf: 'kubectl delete -f',
      kgn: 'kubectl get nodes',
      kgns: 'kubectl get namespaces',
      kga: 'kubectl get all',
      kgi: 'kubectl get ingress',
      kcuc: 'kubectl config use-context',
      kcgc: 'kubectl config get-contexts',
      kgcm: 'kubectl get configmaps',
      kgsec: 'kubectl get secrets',
      krr: 'kubectl rollout restart',
      krs: 'kubectl rollout status',
    },
  },
  lando: {
    description: 'Lando aliases (ported from oh-my-zsh)',
    aliases: {
      la: 'lando',
      las: 'lando start',
      lap: 'lando stop',
      lar: 'lando rebuild',
      lai: 'lando info',
      lal: 'lando logs',
    },
  },
  laravel: {
    description: 'Laravel aliases (ported from oh-my-zsh)',
    aliases: {
      pa: 'php artisan',
      pas: 'php artisan serve',
      pam: 'php artisan migrate',
      pamf: 'php artisan migrate --force',
      pamr: 'php artisan migrate:rollback',
      pams: 'php artisan migrate:status',
      pat: 'php artisan tinker',
      pamk: 'php artisan make',
    },
  },
  laravel4: {
    description: 'Laravel 4 aliases (ported from oh-my-zsh)',
    aliases: {
      la4: 'php artisan',
      la4dump: 'php artisan dump-autoload',
    },
  },
  laravel5: {
    description: 'Laravel 5 aliases (ported from oh-my-zsh)',
    aliases: {
      la5: 'php artisan',
      la5routes: 'php artisan route:list',
      la5cache: 'php artisan cache:clear',
    },
  },
  lein: {
    description: 'Leiningen aliases (ported from oh-my-zsh)',
    aliases: {
      le: 'lein',
      ler: 'lein repl',
      let: 'lein test',
      lec: 'lein clean',
      led: 'lein deps',
    },
  },
  lol: {
    description: 'Fun command aliases (ported from oh-my-zsh)',
    aliases: {
      plz: 'sudo',
      icanhas: 'mkdir',
      gimmeh: 'touch',
      dowant: 'cp',
      nowai: 'rm',
      gtfo: 'mv',
      hai: 'cd',
      kthxbai: 'exit',
    },
  },
  macports: {
    description: 'MacPorts aliases (ported from oh-my-zsh)',
    aliases: {
      pi: 'sudo port install',
      pu: 'sudo port uninstall',
      ps: 'port search',
      psu: 'sudo port selfupdate',
      pup: 'sudo port upgrade outdated',
    },
  },
  man: {
    description: 'Man page aliases (ported from oh-my-zsh)',
    aliases: {
      manp: 'man -P cat',
    },
  },
  mercurial: {
    description: 'Mercurial aliases (ported from oh-my-zsh)',
    aliases: {
      hgs: 'hg status',
      hgd: 'hg diff',
      hgc: 'hg commit',
      hgp: 'hg push',
      hgu: 'hg pull --update',
      hgl: 'hg log',
      hgb: 'hg branch',
    },
  },
  meteor: {
    description: 'Meteor aliases (ported from oh-my-zsh)',
    aliases: {
      mr: 'meteor run',
      ma: 'meteor add',
      mrm: 'meteor remove',
      mu: 'meteor update',
      mt: 'meteor test',
    },
  },
  microk8s: {
    description: 'MicroK8s aliases (ported from oh-my-zsh)',
    aliases: {
      mk: 'microk8s',
      mkk: 'microk8s kubectl',
      mke: 'microk8s enable',
      mkd: 'microk8s disable',
      mks: 'microk8s status',
    },
  },
  minikube: {
    description: 'Minikube aliases (ported from oh-my-zsh)',
    aliases: {
      mkb: 'minikube',
      mkbs: 'minikube start',
      mkbp: 'minikube stop',
      mkbd: 'minikube delete',
      mkbst: 'minikube status',
      mkbssh: 'minikube ssh',
      mkbip: 'minikube ip',
    },
  },
  mise: {
    description: 'mise aliases (ported from oh-my-zsh)',
    aliases: {
      mi: 'mise install',
      mu: 'mise use',
      ml: 'mise list',
      mr: 'mise run',
      mls: 'mise ls',
    },
  },
  mix: {
    description: 'Elixir Mix aliases (ported from oh-my-zsh)',
    aliases: {
      mx: 'mix',
      mxc: 'mix compile',
      mxt: 'mix test',
      mxd: 'mix deps.get',
      mxs: 'mix phx.server',
      mxn: 'mix new',
    },
  },
  molecule: {
    description: 'Ansible Molecule aliases (ported from oh-my-zsh)',
    aliases: {
      mol: 'molecule',
      molt: 'molecule test',
      molc: 'molecule converge',
      mold: 'molecule destroy',
      moll: 'molecule lint',
      molv: 'molecule verify',
    },
  },
  mongocli: {
    description: 'MongoDB CLI aliases (ported from oh-my-zsh)',
    aliases: {
      mg: 'mongocli',
      mga: 'mongocli atlas',
      mgac: 'mongocli atlas clusters',
      mgacl: 'mongocli atlas clusters list',
    },
  },
  mosh: {
    description: 'Mosh aliases (ported from oh-my-zsh)',
    aliases: {
      msh: 'mosh',
    },
  },
  mvn: {
    description: 'Maven aliases (ported from oh-my-zsh)',
    aliases: {
      mvnci: 'mvn clean install',
      mvnc: 'mvn clean',
      mvnt: 'mvn test',
      mvnp: 'mvn package',
      mvnd: 'mvn deploy',
      mvnag: 'mvn archetype:generate',
      mvndt: 'mvn dependency:tree',
    },
  },
  nanoc: {
    description: 'Nanoc aliases (ported from oh-my-zsh)',
    aliases: {
      nc: 'nanoc',
      ncc: 'nanoc compile',
      ncv: 'nanoc view',
    },
  },
  nats: {
    description: 'NATS CLI aliases (ported from oh-my-zsh)',
    aliases: {
      ntp: 'nats pub',
      nts: 'nats sub',
      ntr: 'nats req',
      ntstr: 'nats stream',
      ntcon: 'nats consumer',
    },
  },
  nestjs: {
    description: 'NestJS CLI aliases (ported from oh-my-zsh)',
    aliases: {
      nest: 'nest',
      nestn: 'nest new',
      nestg: 'nest generate',
      nests: 'nest start',
      nestsd: 'nest start --debug',
      nestb: 'nest build',
    },
  },
  ng: {
    description: 'Angular CLI aliases (ported from oh-my-zsh)',
    aliases: {
      ngs: 'ng serve',
      ngb: 'ng build',
      ngt: 'ng test',
      ngg: 'ng generate',
      nge2e: 'ng e2e',
      ngn: 'ng new',
      ngl: 'ng lint',
    },
  },
  ngrok: {
    description: 'ngrok aliases (ported from oh-my-zsh)',
    aliases: {
      ngr: 'ngrok',
      ngrh: 'ngrok http',
      ngrt: 'ngrok tcp',
    },
  },
  nmap: {
    description: 'Nmap aliases (ported from oh-my-zsh)',
    aliases: {
      nms: 'nmap -sS',
      nma: 'nmap -A',
      nmf: 'nmap -sV -sC',
      nmp: 'nmap -Pn',
    },
  },
  node: {
    description: 'Node.js aliases (ported from oh-my-zsh)',
    aliases: {
      nd: 'node',
      ndi: 'node inspect',
    },
  },
  nodenv: {
    description: 'nodenv aliases (ported from oh-my-zsh)',
    aliases: {
      nei: 'nodenv install',
      nel: 'nodenv local',
      neg: 'nodenv global',
      nes: 'nodenv shell',
      nev: 'nodenv versions',
    },
  },
  npm: {
    description: 'npm aliases (ported from oh-my-zsh)',
    aliases: {
      ni: 'npm install',
      nig: 'npm install -g',
      nis: 'npm install --save',
      nisd: 'npm install --save-dev',
      nr: 'npm run',
      nrd: 'npm run dev',
      nrb: 'npm run build',
      nrt: 'npm run test',
      nrs: 'npm start',
      nrp: 'npm publish',
      nau: 'npm audit',
      nauf: 'npm audit fix',
      nu: 'npm update',
      nls: 'npm list',
      nout: 'npm outdated',
    },
  },
  nvm: {
    description: 'nvm aliases (ported from oh-my-zsh)',
    aliases: {
      nvmi: 'nvm install',
      nvmu: 'nvm use',
      nvml: 'nvm list',
      nvmlr: 'nvm ls-remote',
      nvmd: 'nvm alias default',
      nvmc: 'nvm current',
    },
  },
  oc: {
    description: 'OpenShift CLI aliases (ported from oh-my-zsh)',
    aliases: {
      ocp: 'oc project',
      ocl: 'oc login',
      ocg: 'oc get',
      ocd: 'oc describe',
      ocs: 'oc status',
      ocn: 'oc new-project',
    },
  },
  opentofu: {
    description: 'OpenTofu aliases (ported from oh-my-zsh)',
    aliases: {
      ot: 'tofu',
      oti: 'tofu init',
      otp: 'tofu plan',
      ota: 'tofu apply',
      otaa: 'tofu apply -auto-approve',
      otd: 'tofu destroy',
      otf: 'tofu fmt',
      otv: 'tofu validate',
      ots: 'tofu state',
      otsl: 'tofu state list',
    },
  },
  'operator-sdk': {
    description: 'Operator SDK aliases (ported from oh-my-zsh)',
    aliases: {
      osdk: 'operator-sdk',
      osdki: 'operator-sdk init',
      osdkca: 'operator-sdk create api',
      osdkb: 'operator-sdk build',
    },
  },
  paver: {
    description: 'Paver aliases (ported from oh-my-zsh)',
    aliases: {
      pv: 'paver',
    },
  },
  perl: {
    description: 'Perl aliases (ported from oh-my-zsh)',
    aliases: {
      pl: 'perl',
      pd: 'perldoc',
    },
  },
  phing: {
    description: 'Phing aliases (ported from oh-my-zsh)',
    aliases: {
      ph: 'phing',
    },
  },
  pip: {
    description: 'pip aliases (ported from oh-my-zsh)',
    aliases: {
      pipi: 'pip install',
      pipig: 'pip install --upgrade',
      pipu: 'pip uninstall',
      pipf: 'pip freeze',
      pipl: 'pip list',
      pipo: 'pip list --outdated',
      pips: 'pip show',
    },
  },
  pipenv: {
    description: 'Pipenv aliases (ported from oh-my-zsh)',
    aliases: {
      pei: 'pipenv install',
      peid: 'pipenv install --dev',
      peru: 'pipenv run',
      pesh: 'pipenv shell',
      peun: 'pipenv uninstall',
      peup: 'pipenv update',
      peg: 'pipenv graph',
    },
  },
  pj: {
    description: 'Project jump aliases (ported from oh-my-zsh)',
    aliases: {
      pjo: 'pj open',
    },
  },
  pm2: {
    description: 'PM2 aliases (ported from oh-my-zsh)',
    aliases: {
      pms: 'pm2 start',
      pmp: 'pm2 stop',
      pmr: 'pm2 restart',
      pml: 'pm2 list',
      pmlo: 'pm2 logs',
      pmm: 'pm2 monit',
      pmd: 'pm2 delete',
    },
  },
  podman: {
    description: 'Podman aliases (ported from oh-my-zsh)',
    aliases: {
      pd: 'podman',
      pdr: 'podman run',
      pdps: 'podman ps',
      pdpa: 'podman ps -a',
      pdi: 'podman images',
      pdb: 'podman build',
      pdl: 'podman logs',
      pdlf: 'podman logs -f',
      pdst: 'podman stop',
      pdrm: 'podman rm',
      pdrmi: 'podman rmi',
    },
  },
  poetry: {
    description: 'Poetry aliases (ported from oh-my-zsh)',
    aliases: {
      poi: 'poetry install',
      poa: 'poetry add',
      poad: 'poetry add --group dev',
      porr: 'poetry run',
      pos: 'poetry shell',
      pob: 'poetry build',
      pop: 'poetry publish',
      pou: 'poetry update',
      pol: 'poetry lock',
      poex: 'poetry export',
    },
  },
  postgres: {
    description: 'PostgreSQL aliases (ported from oh-my-zsh)',
    aliases: {
      pgs: 'pg_isready',
      pgcli: 'pgcli',
      psql: 'psql',
    },
  },
  'pre-commit': {
    description: 'pre-commit aliases (ported from oh-my-zsh)',
    aliases: {
      pci: 'pre-commit install',
      pcr: 'pre-commit run',
      pcra: 'pre-commit run --all-files',
      pcu: 'pre-commit autoupdate',
    },
  },
  procs: {
    description: 'procs aliases (ported from oh-my-zsh)',
    aliases: {
      pp: 'procs',
      ppw: 'procs --watch',
      ppt: 'procs --tree',
    },
  },
  pulumi: {
    description: 'Pulumi aliases (ported from oh-my-zsh)',
    aliases: {
      pu: 'pulumi',
      puu: 'pulumi up',
      pup: 'pulumi preview',
      pud: 'pulumi destroy',
      pus: 'pulumi stack',
      pusl: 'pulumi stack ls',
      puc: 'pulumi config',
    },
  },
  pyenv: {
    description: 'pyenv aliases (ported from oh-my-zsh)',
    aliases: {
      pyi: 'pyenv install',
      pyl: 'pyenv local',
      pyg: 'pyenv global',
      pyv: 'pyenv versions',
      pys: 'pyenv shell',
    },
  },
  python: {
    description: 'Python aliases (ported from oh-my-zsh)',
    aliases: {
      py: 'python3',
      py2: 'python2',
      pym: 'python3 -m',
      pyhttp: 'python3 -m http.server',
      pyjson: 'python3 -m json.tool',
      pyvenv: 'python3 -m venv',
      pypip: 'python3 -m pip',
    },
  },
  rails: {
    description: 'Ruby on Rails aliases (ported from oh-my-zsh)',
    aliases: {
      rc: 'rails console',
      rdb: 'rails dbconsole',
      rg: 'rails generate',
      rgm: 'rails generate migration',
      rs: 'rails server',
      rsd: 'rails server --debugger',
      rr: 'rails routes',
      rdm: 'rails db:migrate',
      rds: 'rails db:seed',
      rdr: 'rails db:rollback',
    },
  },
  rake: {
    description: 'Rake aliases (ported from oh-my-zsh)',
    aliases: {
      rk: 'rake',
      rkdb: 'rake db:migrate',
      rkdbs: 'rake db:seed',
      rkt: 'rake test',
    },
  },
  rbenv: {
    description: 'rbenv aliases (ported from oh-my-zsh)',
    aliases: {
      rbi: 'rbenv install',
      rbl: 'rbenv local',
      rbg: 'rbenv global',
      rbv: 'rbenv versions',
      rbs: 'rbenv shell',
    },
  },
  rclone: {
    description: 'rclone aliases (ported from oh-my-zsh)',
    aliases: {
      rcl: 'rclone',
      rcls: 'rclone sync',
      rclc: 'rclone copy',
      rclls: 'rclone ls',
    },
  },
  'react-native': {
    description: 'React Native aliases (ported from oh-my-zsh)',
    aliases: {
      rn: 'npx react-native',
      rns: 'npx react-native start',
      rnr: 'npx react-native run-android',
      rnri: 'npx react-native run-ios',
      rnl: 'npx react-native log-android',
      rnli: 'npx react-native log-ios',
    },
  },
  'redis-cli': {
    description: 'Redis CLI aliases (ported from oh-my-zsh)',
    aliases: {
      rdcli: 'redis-cli',
      rds: 'redis-server',
    },
  },
  rsync: {
    description: 'rsync aliases (ported from oh-my-zsh)',
    aliases: {
      rscp: 'rsync -avz --progress',
      rsmv: 'rsync -avz --progress --remove-source-files',
    },
  },
  ruby: {
    description: 'Ruby aliases (ported from oh-my-zsh)',
    aliases: {
      rb: 'ruby',
      rbi: 'ruby -e "require \'irb\'; IRB.start"',
    },
  },
  rust: {
    description: 'Rust/Cargo aliases (ported from oh-my-zsh)',
    aliases: {
      cb: 'cargo build',
      cbr: 'cargo build --release',
      cr: 'cargo run',
      crr: 'cargo run --release',
      ct: 'cargo test',
      cc: 'cargo check',
      ccl: 'cargo clippy',
      cf: 'cargo fmt',
      cn: 'cargo new',
      ca: 'cargo add',
      cu: 'cargo update',
      cd: 'cargo doc',
      cdo: 'cargo doc --open',
    },
  },
  rvm: {
    description: 'RVM aliases (ported from oh-my-zsh)',
    aliases: {
      rvmu: 'rvm use',
      rvmi: 'rvm install',
      rvml: 'rvm list',
      rvmg: 'rvm gemset',
    },
  },
  salt: {
    description: 'SaltStack aliases (ported from oh-my-zsh)',
    aliases: {
      sa: 'salt',
      sak: 'salt-key',
      sac: 'salt-call',
      sar: 'salt-run',
    },
  },
  scala: {
    description: 'Scala aliases (ported from oh-my-zsh)',
    aliases: {
      sc: 'scala',
      scc: 'scalac',
      sbt: 'sbt',
      sbtt: 'sbt test',
      sbtc: 'sbt compile',
      sbtr: 'sbt run',
    },
  },
  scw: {
    description: 'Scaleway CLI aliases (ported from oh-my-zsh)',
    aliases: {
      scw: 'scw',
      scwi: 'scw instance',
      scwil: 'scw instance server list',
      scwk: 'scw k8s',
      scwkl: 'scw k8s cluster list',
    },
  },
  sdk: {
    description: 'SDKMAN aliases (ported from oh-my-zsh)',
    aliases: {
      sdki: 'sdk install',
      sdku: 'sdk use',
      sdkl: 'sdk list',
      sdkc: 'sdk current',
      sdkd: 'sdk default',
    },
  },
  sfdx: {
    description: 'Salesforce DX aliases (ported from oh-my-zsh)',
    aliases: {
      sfdx: 'sfdx',
      sfp: 'sfdx force:source:push',
      sfpl: 'sfdx force:source:pull',
      sfo: 'sfdx force:org:open',
      sfl: 'sfdx force:org:list',
    },
  },
  skaffold: {
    description: 'Skaffold aliases (ported from oh-my-zsh)',
    aliases: {
      skd: 'skaffold dev',
      skr: 'skaffold run',
      skb: 'skaffold build',
      skdel: 'skaffold delete',
    },
  },
  snap: {
    description: 'Snap aliases (ported from oh-my-zsh)',
    aliases: {
      sni: 'sudo snap install',
      snr: 'sudo snap remove',
      snl: 'snap list',
      snf: 'snap find',
      snu: 'sudo snap refresh',
    },
  },
  spring: {
    description: 'Spring Boot aliases (ported from oh-my-zsh)',
    aliases: {
      spr: 'spring run',
      spi: 'spring init',
    },
  },
  stripe: {
    description: 'Stripe CLI aliases (ported from oh-my-zsh)',
    aliases: {
      stl: 'stripe listen',
      stlf: 'stripe listen --forward-to',
      stlg: 'stripe logs tail',
      ste: 'stripe events',
    },
  },
  sublime: {
    description: 'Sublime Text aliases (ported from oh-my-zsh)',
    aliases: {
      st: 'subl',
      stt: 'subl .',
      stn: 'subl --new-window',
    },
  },
  svn: {
    description: 'Subversion aliases (ported from oh-my-zsh)',
    aliases: {
      svns: 'svn status',
      svnc: 'svn commit',
      svnu: 'svn update',
      svna: 'svn add',
      svnd: 'svn diff',
      svnl: 'svn log',
    },
  },
  swiftpm: {
    description: 'Swift Package Manager aliases (ported from oh-my-zsh)',
    aliases: {
      spb: 'swift build',
      spt: 'swift test',
      spr: 'swift run',
      spp: 'swift package',
      sppi: 'swift package init',
      sppu: 'swift package update',
    },
  },
  symfony: {
    description: 'Symfony aliases (ported from oh-my-zsh)',
    aliases: {
      sf: 'symfony',
      sfs: 'symfony serve',
      sfc: 'symfony console',
    },
  },
  symfony2: {
    description: 'Symfony 2 aliases (ported from oh-my-zsh)',
    aliases: {
      sf2: 'php app/console',
      sf2cc: 'php app/console cache:clear',
    },
  },
  symfony6: {
    description: 'Symfony 6 aliases (ported from oh-my-zsh)',
    aliases: {
      sf6: 'php bin/console',
      sf6cc: 'php bin/console cache:clear',
      sf6mm: 'php bin/console make:migration',
      sf6dm: 'php bin/console doctrine:migrations:migrate',
    },
  },
  systemadmin: {
    description: 'System admin aliases (ported from oh-my-zsh)',
    aliases: {
      psg: 'ps aux | grep',
      dud: 'du -d 1 -h',
      duf: 'du -sh',
      fdr: 'find . -type d -name',
      ffr: 'find . -type f -name',
    },
  },
  systemd: {
    description: 'Systemd aliases (ported from oh-my-zsh)',
    aliases: {
      sc: 'systemctl',
      scs: 'systemctl status',
      scr: 'sudo systemctl restart',
      sce: 'sudo systemctl enable',
      scd: 'sudo systemctl disable',
      scst: 'sudo systemctl start',
      scsp: 'sudo systemctl stop',
      scrl: 'sudo systemctl reload',
      jc: 'journalctl',
      jcf: 'journalctl -f',
    },
  },
  tailscale: {
    description: 'Tailscale aliases (ported from oh-my-zsh)',
    aliases: {
      ts: 'tailscale',
      tss: 'tailscale status',
      tsu: 'tailscale up',
      tsd: 'tailscale down',
      tsip: 'tailscale ip',
    },
  },
  task: {
    description: 'Taskfile aliases (ported from oh-my-zsh)',
    aliases: {
      tk: 'task',
      tkl: 'task --list',
    },
  },
  taskwarrior: {
    description: 'Taskwarrior aliases (ported from oh-my-zsh)',
    aliases: {
      tw: 'task',
      twa: 'task add',
      twl: 'task list',
      twd: 'task done',
      twm: 'task modify',
    },
  },
  terraform: {
    description: 'Terraform aliases (ported from oh-my-zsh)',
    aliases: {
      tf: 'terraform',
      tfi: 'terraform init',
      tfp: 'terraform plan',
      tfa: 'terraform apply',
      tfaa: 'terraform apply -auto-approve',
      tfd: 'terraform destroy',
      tff: 'terraform fmt',
      tfv: 'terraform validate',
      tfs: 'terraform state',
      tfsl: 'terraform state list',
      tfo: 'terraform output',
      tfw: 'terraform workspace',
      tfwl: 'terraform workspace list',
      tfws: 'terraform workspace select',
    },
  },
  tig: {
    description: 'Tig aliases (ported from oh-my-zsh)',
    aliases: {
      tg: 'tig',
      tgs: 'tig status',
      tgb: 'tig blame',
    },
  },
  timoni: {
    description: 'Timoni aliases (ported from oh-my-zsh)',
    aliases: {
      tma: 'timoni apply',
      tmb: 'timoni build',
      tml: 'timoni list',
      tmd: 'timoni delete',
    },
  },
  tldr: {
    description: 'tldr aliases (ported from oh-my-zsh)',
    aliases: {
      tldr: 'tldr',
    },
  },
  tmux: {
    description: 'tmux aliases (ported from oh-my-zsh)',
    aliases: {
      ta: 'tmux attach -t',
      tad: 'tmux attach -d -t',
      tks: 'tmux kill-session -t',
      tkss: 'tmux kill-server',
      tl: 'tmux list-sessions',
      tn: 'tmux new-session -s',
      ts: 'tmux new-session -s',
    },
  },
  tmuxinator: {
    description: 'Tmuxinator aliases (ported from oh-my-zsh)',
    aliases: {
      mux: 'tmuxinator',
      muxs: 'tmuxinator start',
      muxo: 'tmuxinator open',
      muxn: 'tmuxinator new',
      muxl: 'tmuxinator list',
      muxe: 'tmuxinator edit',
      muxd: 'tmuxinator delete',
    },
  },
  uv: {
    description: 'uv Python package manager aliases (ported from oh-my-zsh)',
    aliases: {
      uvi: 'uv pip install',
      uvr: 'uv run',
      uvs: 'uv sync',
      uva: 'uv add',
      uvad: 'uv add --dev',
      uvl: 'uv lock',
      uvv: 'uv venv',
    },
  },
  vagrant: {
    description: 'Vagrant aliases (ported from oh-my-zsh)',
    aliases: {
      vg: 'vagrant',
      vgu: 'vagrant up',
      vgd: 'vagrant destroy',
      vgs: 'vagrant ssh',
      vgst: 'vagrant status',
      vgh: 'vagrant halt',
      vgp: 'vagrant provision',
      vgr: 'vagrant reload',
      vggs: 'vagrant global-status',
    },
  },
  vault: {
    description: 'HashiCorp Vault aliases (ported from oh-my-zsh)',
    aliases: {
      vl: 'vault login',
      vr: 'vault read',
      vw: 'vault write',
      vd: 'vault delete',
      vls: 'vault list',
      vs: 'vault server',
      vsd: 'vault server -dev',
      vst: 'vault status',
    },
  },
  volta: {
    description: 'Volta aliases (ported from oh-my-zsh)',
    aliases: {
      vli: 'volta install',
      vlp: 'volta pin',
      vll: 'volta list',
      vlr: 'volta run',
    },
  },
  vscode: {
    description: 'VS Code aliases (ported from oh-my-zsh)',
    aliases: {
      vsc: 'code',
      vscd: 'code --diff',
      vscn: 'code --new-window',
      vscr: 'code --reuse-window',
      vsca: 'code --add',
      vsci: 'code --install-extension',
      vscu: 'code --uninstall-extension',
    },
  },
  'wp-cli': {
    description: 'WP-CLI aliases (ported from oh-my-zsh)',
    aliases: {
      wpp: 'wp plugin',
      wppl: 'wp plugin list',
      wppi: 'wp plugin install',
      wppa: 'wp plugin activate',
      wpt: 'wp theme',
      wptl: 'wp theme list',
    },
  },
  xcode: {
    description: 'Xcode aliases (ported from oh-my-zsh)',
    aliases: {
      xb: 'xcodebuild',
      xbc: 'xcodebuild clean',
      xbt: 'xcodebuild test',
      xcdd: 'rm -rf ~/Library/Developer/Xcode/DerivedData',
    },
  },
  yarn: {
    description: 'Yarn aliases (ported from oh-my-zsh)',
    aliases: {
      y: 'yarn',
      ya: 'yarn add',
      yad: 'yarn add --dev',
      yrm: 'yarn remove',
      yr: 'yarn run',
      yrd: 'yarn run dev',
      yrb: 'yarn run build',
      yrt: 'yarn run test',
      ys: 'yarn start',
      yu: 'yarn upgrade',
      yui: 'yarn upgrade-interactive',
      yga: 'yarn global add',
      ygr: 'yarn global remove',
    },
  },
  yum: {
    description: 'Yum aliases (ported from oh-my-zsh)',
    aliases: {
      yi: 'sudo yum install',
      yr: 'sudo yum remove',
      yu: 'sudo yum update',
      ys: 'yum search',
      yl: 'yum list installed',
    },
  },
  zoxide: {
    description: 'Zoxide aliases (ported from oh-my-zsh)',
    aliases: {
      z: 'zoxide query',
      zi: 'zoxide query -i',
      za: 'zoxide add',
      zr: 'zoxide remove',
    },
  },
  brew: {
    description: 'Homebrew aliases (macOS only, partial)',
    aliases: {
      bri: 'brew install',
      bris: 'brew install --cask',
      bru: 'brew uninstall',
      brup: 'brew update',
      brug: 'brew upgrade',
      brs: 'brew search',
      brl: 'brew list',
      brd: 'brew doctor',
      bro: 'brew outdated',
      brci: 'brew info',
    },
  },
  macos: {
    description: 'macOS utility aliases (partial)',
    aliases: {
      showfiles: 'defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder',
      hidefiles: 'defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder',
      flushdns: 'sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder',
      cleanup: 'find . -type f -name "*.DS_Store" -ls -delete',
      emptytrash: 'sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash',
    },
  },
  ubuntu: {
    description: 'Ubuntu aliases (partial)',
    aliases: {
      agi: 'sudo apt install',
      agr: 'sudo apt remove',
      agu: 'sudo apt update',
      agug: 'sudo apt upgrade',
      agdu: 'sudo apt dist-upgrade',
      acs: 'apt search',
    },
  },
  archlinux: {
    description: 'Arch Linux aliases (partial)',
    aliases: {
      paci: 'sudo pacman -S',
      pacr: 'sudo pacman -Rns',
      pacs: 'pacman -Ss',
      pacu: 'sudo pacman -Syu',
      pacq: 'pacman -Qi',
      pacl: 'pacman -Ql',
    },
  },
  suse: {
    description: 'openSUSE aliases (partial)',
    aliases: {
      zi: 'sudo zypper install',
      zr: 'sudo zypper remove',
      zu: 'sudo zypper update',
      zs: 'zypper search',
      zdup: 'sudo zypper dup',
    },
  },
}
